# Generated by Django 6.0 on 2026-01-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skill_code', models.CharField(choices=[('LISTENING_PICTURE', 'Listening – Picture'), ('LISTENING_QA', 'Listening – Question & Answer'), ('LISTENING_CONVERSATION', 'Listening – Conversation'), ('LISTENING_INFORMATION', 'Listening – Information'), ('READING_SENTENCE', 'Reading – Sentence Completion'), ('READING_TEXT', 'Reading – Text Completion'), ('READING_PASSAGE', 'Reading – Reading Comprehension')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('quiz_type', models.CharField(choices=[('PRACTICE', 'Practice'), ('QUIZ', 'Quiz'), ('MOCK', 'Mock Test')], max_length=20)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Seconds', null=True)),
                ('total_questions', models.PositiveIntegerField()),
                ('pass_score', models.PositiveIntegerField(default=70)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
