# Generated by Django 6.0 on 2026-01-04 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='total_questions',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='skill_code',
            field=models.CharField(choices=[('LISTENING_PICTURE', 'Listening Picture'), ('LISTENING_QA', 'Listening Qa'), ('LISTENING_CONVERSATION', 'Listening Conversation'), ('LISTENING_INFORMATION', 'Listening Information'), ('READING_SENTENCE', 'Reading Sentence'), ('READING_TEXT', 'Reading Text'), ('READING_PASSAGE', 'Reading Passage')], max_length=50),
        ),
        migrations.CreateModel(
            name='QuestionForQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('passage', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_for_quiz', to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.questionforquiz')),
            ],
        ),
    ]
