# Generated by Django 6.0 on 2026-01-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_room_options_question_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='context',
            field=models.CharField(blank=True, help_text="e.g., 'coding', 'debugging', 'agile meetings'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='directive',
            field=models.TextField(blank=True, help_text="e.g., 'Choose the best word/phrase to complete the sentence:'", null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Detailed explanation why the answer is correct', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('sentence_completion', 'Sentence Completion')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0, help_text='Points for correct answer (0-10)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
    ]
