# Generated by Django 6.0 on 2026-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_context_question_directive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='elo_updated',
            field=models.BooleanField(default=False, help_text='Whether ELO has been calculated and applied'),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player1_elo_after',
            field=models.IntegerField(blank=True, help_text='Player1 ELO after match', null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player1_elo_before',
            field=models.IntegerField(blank=True, help_text='Player1 ELO before match', null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player1_elo_change',
            field=models.IntegerField(default=0, help_text='Player1 ELO change'),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player2_elo_after',
            field=models.IntegerField(blank=True, help_text='Player2 ELO after match', null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player2_elo_before',
            field=models.IntegerField(blank=True, help_text='Player2 ELO before match', null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player2_elo_change',
            field=models.IntegerField(default=0, help_text='Player2 ELO change'),
        ),
    ]
