# Generated by Django 6.0 on 2026-01-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.CharField(blank=True, choices=[('reading', 'Đọc sách'), ('movies', 'Xem phim'), ('music', 'Nghe nhạc'), ('sports', 'Thể thao'), ('travel', 'Du lịch'), ('cooking', 'Nấu ăn'), ('gaming', 'Chơi game'), ('art', 'Vẽ/Thủ công mỹ nghệ'), ('photography', 'Nhiếp ảnh'), ('gardening', 'Làm vườn'), ('fitness', 'Tập gym/Yoga'), ('walking', 'Đi bộ/Chạy bộ'), ('writing', 'Viết lách'), ('collecting', 'Sưu tầm')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, choices=[('1/12', '1/12'), ('2/12', '2/12'), ('3/12', '3/12'), ('4/12', '4/12'), ('5/12', '5/12'), ('6/12', '6/12'), ('7/12', '7/12'), ('8/12', '8/12'), ('9/12', '9/12'), ('10/12', '10/12'), ('11/12', '11/12'), ('12/12', '12/12'), ('college', 'Cao đẳng'), ('university', 'Đại học'), ('master', 'Thạc sĩ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goals',
            field=models.CharField(blank=True, choices=[('study_abroad', 'Du học'), ('job', 'Công việc'), ('exam', 'Thi cử'), ('communication', 'Giao tiếp')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, choices=[('student', 'Học sinh/Sinh viên'), ('teacher', 'Giáo viên'), ('engineer', 'Kỹ sư'), ('other', 'Khác')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng')], max_length=50, null=True),
        ),
    ]
