# Generated by Django 6.0 on 2026-01-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_hobby_alter_user_education_alter_user_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elo_rating',
            field=models.IntegerField(default=1000, help_text='Player ELO rating for quiz battles'),
        ),
    ]
