# Generated by Django 6.0 on 2026-01-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_ai_battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ai_difficulty',
            field=models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó'), ('expert', 'Chuyên gia')], default='medium', max_length=10),
        ),
    ]
