# Generated by Django 6.0 on 2026-01-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_ai_battle', '0002_match_ai_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elo_after',
            field=models.IntegerField(blank=True, help_text='User ELO after match', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='elo_before',
            field=models.IntegerField(blank=True, help_text='User ELO before match', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='elo_change',
            field=models.IntegerField(default=0, help_text='ELO points gained/lost in this match'),
        ),
    ]
