# Generated by Django 6.0 on 2025-12-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_ai_battle', '0002_alter_match_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ai_mode',
            field=models.CharField(choices=[('random', 'Random AI'), ('gpt', 'GPT AI')], default='random', max_length=10),
        ),
    ]
