# Generated by Django 6.0 on 2026-01-02 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrance_test', '0003_questionimage_alter_entrancetestresult_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='TOEIC skill or part, e.g. PART_1_LISTENING', max_length=50)),
                ('section', models.CharField(choices=[('LISTENING', 'Listening'), ('READING', 'Reading')], max_length=20)),
                ('accuracy', models.FloatField(help_text='Correct rate from 0.0 to 1.0')),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profiles', to='entrance_test.entrancetestresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
