# Generated by Django 6.0 on 2026-01-02 02:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_test', '0003_questionimage_alter_entrancetestresult_options_and_more'),
        ('learning_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskillprofile',
            unique_together={('user', 'result', 'skill')},
        ),
    ]
