# Generated by Django 6.0 on 2026-01-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_profile', '0002_alter_userskillprofile_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskillprofile',
            name='skill',
            field=models.CharField(choices=[('LISTENING_PICTURE', 'Listening Picture'), ('LISTENING_QA', 'Listening Qa'), ('LISTENING_CONVERSATION', 'Listening Conversation'), ('LISTENING_INFORMATION', 'Listening Information'), ('READING_SENTENCE', 'Reading Sentence'), ('READING_TEXT', 'Reading Text'), ('READING_PASSAGE', 'Reading Passage')], help_text='TOEIC skill or part, e.g. PART_1_LISTENING', max_length=50),
        ),
    ]
