from django.db import models

class SkillCode(models.TextChoices):
    LISTENING_PICTURE = 'LISTENING_PICTURE'
    LISTENING_QA = 'LISTENING_QA'
    LISTENING_CONVERSATION = 'LISTENING_CONVERSATION'
    LISTENING_INFORMATION = 'LISTENING_INFORMATION'
    READING_SENTENCE = 'READING_SENTENCE'
    READING_TEXT = 'READING_TEXT'
    READING_PASSAGE = 'READING_PASSAGE'


class SkillLevel(models.TextChoices):
    BEGINNER = 'BEGINNER'
    ELEMENTARY = 'ELEMENTARY'
    INTERMEDIATE = 'INTERMEDIATE'
    ADVANCED = 'ADVANCED'

class LearningPathItemStatus(models.TextChoices):
    LOCKED = "LOCKED"
    UNLOCKED = "UNLOCKED"
    COMPLETED = "COMPLETED"