# Generated by Django 6.0 on 2026-01-23 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, help_text='Task ID from AI worker', max_length=100, unique=True)),
                ('quiz_size', models.IntegerField(default=10, help_text='Number of questions to generate')),
                ('declared_level', models.CharField(help_text='English proficiency level (Beginner, Advanced, etc.)', max_length=50)),
                ('profession', models.CharField(blank=True, help_text="User's profession (engineer, teacher, student, etc.)", max_length=100)),
                ('goals', models.CharField(blank=True, help_text='Learning goal (job, exam, communication, etc.)', max_length=50)),
                ('preferred_topics', models.JSONField(default=list, help_text='List of topics user wants to practice')),
                ('weak_skills', models.JSONField(default=list, help_text='List of weak areas to focus on')),
                ('extra_instructions', models.TextField(blank=True, help_text='Additional instructions for AI to consider')),
                ('status', models.CharField(choices=[('queued', 'Queued - Chờ xử lý'), ('processing', 'Processing - Đang xử lý'), ('completed', 'Completed - Hoàn tất'), ('failed', 'Failed - Lỗi')], db_index=True, default='queued', help_text='Current status of the task', max_length=20)),
                ('questions_created', models.IntegerField(default=0, help_text='Number of questions successfully created')),
                ('error_message', models.TextField(blank=True, help_text='Error message if task failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When task was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When AI worker started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When task was completed', null=True)),
                ('worker_response', models.JSONField(default=dict, help_text='Full response from AI worker')),
                ('processing_time_sec', models.IntegerField(blank=True, help_text='Time taken by AI worker (seconds)', null=True)),
                ('user', models.ForeignKey(help_text='User who requested the quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Generation Task',
                'verbose_name_plural': 'Quiz Generation Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='question_ge_user_id_48ebe8_idx'), models.Index(fields=['status', '-created_at'], name='question_ge_status_cf8d36_idx'), models.Index(fields=['task_id'], name='question_ge_task_id_0acd2a_idx')],
            },
        ),
    ]
