# Generated by Django 6.0 on 2026-01-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skill_code', models.CharField(choices=[('LISTENING_PICTURE', 'Listening – Picture'), ('LISTENING_QA', 'Listening – Question & Answer'), ('LISTENING_CONVERSATION', 'Listening – Conversation'), ('LISTENING_INFORMATION', 'Listening – Information'), ('READING_SENTENCE', 'Reading – Sentence Completion'), ('READING_TEXT', 'Reading – Text Completion'), ('READING_PASSAGE', 'Reading – Reading Comprehension')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('estimated_time', models.PositiveIntegerField(help_text='Minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
