# Generated by Django 6.0 on 2026-01-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='skill_code',
            field=models.CharField(choices=[('LISTENING_PICTURE', 'Listening Picture'), ('LISTENING_QA', 'Listening Qa'), ('LISTENING_CONVERSATION', 'Listening Conversation'), ('LISTENING_INFORMATION', 'Listening Information'), ('READING_SENTENCE', 'Reading Sentence'), ('READING_TEXT', 'Reading Text'), ('READING_PASSAGE', 'Reading Passage')], max_length=50),
        ),
    ]
