# Generated by Django 6.0 on 2026-01-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.TextField(blank=True, help_text='Conversation / Short talk / Reading passage', null=True),
        ),
    ]
