# Generated by Django 6.0 on 2026-01-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_test', '0002_question_passage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='toeic_image/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='entrancetestresult',
            options={'ordering': ['-taken_at']},
        ),
        migrations.RemoveConstraint(
            model_name='choice',
            name='only_one_correct_choice',
        ),
        migrations.AlterUniqueTogether(
            name='entrancetestresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('result', 'question')},
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question', 'is_correct'), name='only_one_correct_choice_per_question'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrance_test.questionimage'),
        ),
    ]
