# Generated by Django 6.0 on 2026-01-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpathitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
