# Generated by Django 6.0 on 2026-01-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0002_learningpathitem_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpathitem',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
