# Generated by Django 6.0 on 2026-01-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('learning_path', '0003_alter_learningpathitem_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpathitem',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='learningpathitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningpathitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='learningpathitem',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=10),
        ),
        migrations.AlterField(
            model_name='learningpathitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
