# Generated by Django 6.0 on 2026-01-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0004_remove_learningpathitem_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpathitem',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20),
        ),
    ]
