# Generated by Django 6.0 on 2026-01-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='config',
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigames.question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='minigames.question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='tags',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='vocabularies', to='minigames.tag'),
        ),
    ]
