# Generated by Django 6.0 on 2026-01-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0002_tag_remove_gamesession_config_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('flashcard', 'Flashcard')], max_length=50),
        ),
    ]
