# Generated by Django 6.0 on 2026-01-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0003_attempt_revealed_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='remembered',
            field=models.BooleanField(null=True),
        ),
    ]
